//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Love_Gid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Sum_only_contract { get; set; }
        public int Sum_plus { get; set; }
        public int Received { get; set; }
        public System.DateTime Date_of_event { get; set; }
        public System.DateTime Date_of_sign { get; set; }
        public System.DateTime Payment1 { get; set; }
        public System.DateTime Payment2 { get; set; }
        public System.DateTime Payment3 { get; set; }
        public string Comment { get; set; }
        public int IdEvent { get; set; }
        public int IdEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Event Event { get; set; }
        public virtual Client Client { get; set; }
        public virtual Payments Payments { get; set; }
    }
}
