//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Love_Gid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.PaymentToPeersSet = new HashSet<PaymentToPeers>();
            this.Payments = new HashSet<Payments>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Sum_only_contract { get; set; }
        public int Sum_plus { get; set; }
        public int Received { get; set; }
        public Nullable<System.DateTime> Date_of_event { get; set; }
        public System.DateTime Date_of_sign { get; set; }
        public Nullable<System.DateTime> Payment1Date { get; set; }
        public Nullable<System.DateTime> Payment2Date { get; set; }
        public Nullable<System.DateTime> Payment3Date { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public Nullable<int> Payment1Sum { get; set; }
        public Nullable<int> Payment2Sum { get; set; }
        public Nullable<int> Payment3Sum { get; set; }
    
        public virtual Client ClientSet { get; set; }
        public virtual Employee EmployeeSet { get; set; }
        public virtual Event EventSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentToPeers> PaymentToPeersSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
