//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Love_Gid
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentEmployeeConnect
    {
        public int Id { get; set; }
    
        public virtual Payments Payments { get; set; }
        public virtual Event Event { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
