//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Love_Gid
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentToPeers
    {
        public int Id { get; set; }
        public int Sum { get; set; }
        public int IdToEmployee { get; set; }
        public int IdContract { get; set; }
        public System.DateTime Month { get; set; }
        public string Comment { get; set; }
    
        public virtual Event EventSet { get; set; }
        public virtual Contract ContractSet { get; set; }
    }
}
