//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Love_Gid
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryPerMonth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalaryPerMonth()
        {
            this.CurMonthSal = 0;
            this.CurMonthSalFact = 0;
        }
    
        public int Id { get; set; }
        public Nullable<int> CurMonthSal { get; set; }
        public Nullable<int> CurMonthSalFact { get; set; }
        public Nullable<short> DateMonth { get; set; }
        public Nullable<int> DateYear { get; set; }
        public int IncomeToCompany { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
